---
# MegaLinter GitLab CI job configuration file
# More info at https://megalinter.io
mega-linter:
  artifacts:
    expire_in: 1 week
    paths:
      - report
    when: always
  # You can override MegaLinter flavor used to have faster performances
  # More info at https://megalinter.io/latest/flavors/
  image: oxsecurity/megalinter:v9
  # if script: ["true"] does not work, you may try this instead:
  #   script: [ "/bin/bash /entrypoint.sh" ]
  script:
    - "true"
  stage: test
  variables:
    # All available variables are described in documentation
    # https://megalinter.io/latest/config-file/
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    # Disable LLM Advisor for bot MRs (merge-train, dependabot, renovate, etc.)
    LLM_ADVISOR_ENABLED: |-
      ${CI_PIPELINE_SOURCE != 'merge_request_event' ||
        (CI_MERGE_REQUEST_SOURCE_PROJECT_PATH == CI_PROJECT_PATH &&
         CI_MERGE_REQUEST_AUTHOR_LOGIN !~ /^(dependabot|renovate|github-actions)(\[bot\])?$/ &&
         CI_MERGE_REQUEST_TITLE !~ /^(chore|fix|deps?|bump)(\(.*\))?: /)}
    # ADD YOUR CUSTOM ENV VARIABLES HERE TO OVERRIDE VALUES OF .mega-linter.yml
    # AT THE ROOT OF YOUR REPOSITORY
