branch_whitelist = []
disable_bump_commit = false
disable_changelog = false
from_latest_tag = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
ignore_fixup_commits = false
ignore_merge_commits = false
post_bump_hooks = []
post_package_bump_hooks = []
pre = "alpha.*"
pre_bump_hooks = [
  "bunx prettier --write .",
  "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
]
pre_package_bump_hooks = []
scopes = [
  "cocogitto",
  "copier",
  "cspell",
  "github",
  "jscpd",
  "megalinter",
  "pre-commit",
  "vscode",
  "zed",
]
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[bump_profiles]

[changelog]
authors = [{ signature = "ask.mrdgh2821@outlook.com", username = "MRDGH2821" }]
owner = "MRDGH2821"
path = "CHANGELOG.md"
template = "remote"

[commit_types]

[git_hooks]

[packages]
