branch_whitelist = []
disable_bump_commit = false
disable_changelog = false
from_latest_tag = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
ignore_fixup_commits = false
ignore_merge_commits = false
post_bump_hooks = []
post_package_bump_hooks = []
pre = "alpha.*"
pre_bump_hooks = ["bunx prettier --write ."]
pre_package_bump_hooks = []
scopes = [
  "cocogitto",
  "copier",
  "cspell",
  "github",
  "jscpd",
  "megalinter",
  "pre-commit",
  "vscode",
  "zed",
]
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[bump_profiles]

[changelog]
authors = [{ signature = "MRDGH2821", username = "MRDGH2821" }]
owner = "MRDGH2821"
path = "CHANGELOG.md"
remote = "github.com"
repository = "copier-mr-minimal"
template = "default"

[commit_types]

[git_hooks]

[packages]
